### PR TITLE
Version 1.0.10 - Update dependencies

### PR DESCRIPTION
**Pull request by chrroberts-pure**
- Updates for our dependencies, no current CVEs per Quay scanner. 

- May resolve an issue with the error `fatal error: concurrent map iteration and map write` that was due to a Prometheus dependencies issue.

Has been tested with `docker build` and `go make` with live FlashArrays.

### CODE REVIEW

**Comment by sdodsley** [comment]
Can we test with `podman` as well?

**Review by sdodsley — APPROVED** [review]
LGTM

**Comment by chrroberts-pure** [comment]
I've updated again since this has not been pushed yet. No CVEs detected currently.

I also don't believe that `May resolve an issue with the error fatal error: concurrent map iteration and map write that was due to a Prometheus dependencies issue.` is correct - please disregard

**Comment by chrroberts-pure** [comment]
doc update has been completed as well. ready to merge, but let me check out #84 and review to push that one out with v1.10 as well.

**Comment by chrroberts-pure** [comment]
also this has been tested with `make build` and `make docker-image` on a lab FlashArray

**Pull request merged**
