### PR TITLE
Fixed issue #45 (alerts collector)

### PR DESCRIPTION
**Pull request by genegr**
Fixed issue with open alerts collector.

### CODE REVIEW

**Review by sdodsley — APPROVED** [review]

**Comment by chrroberts-pure** [comment]
Consider adding the ARG for version in the Dockerfile like I did in https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/pull/21

**Comment by sdodsley** [comment]
We have to be consistent across the 2 exporters. So lets pick one and stick with it

**Comment by chrroberts-pure** [comment]
> We have to be consistent across the 2 exporters. So lets pick one and stick with it

Agree.

**Comment by chrroberts-pure** [comment]
The changes to the alert collector removes the label component_name to purefa_alerts_open

ex. before the changes

````
# HELP purefa_alerts_open FlashArray open alert events
# TYPE purefa_alerts_open gauge
purefa_alerts_open{component_name="vasa.certs",component_type="storage",severity="critical"} 1
````

After this change

````
# HELP purefa_alerts_open FlashArray open alert events
# TYPE purefa_alerts_open gauge
purefa_alerts_open{component_type="storage",severity="critical"} 1
````

maybe that's okay, because it's just a hint really to look into purity -- but I think this requires further discussion before approval.

**Comment by chrroberts-pure** [comment]
I also think that if we're also changing how versioning works, we should bump up to use v1.0.6

**Comment by chrroberts-pure** [comment]
any update on this @genegr @sdodsley

**Comment by sdodsley** [comment]
Bump the version

**Pull request merged**
