### PR TITLE
Added specific User-Agent to the REST client

### PR DESCRIPTION
**Pull request by genegr**
Added the proper exporter HTTP User-Agent and updated all the tests to reflect the new internal JSON format of the metric object.
Added TLS support as per issue #70

### CODE REVIEW

**Comment by james-laing** [comment]
I will get round to testing this soon.

**Comment by chrroberts-pure** [comment]
I will test as is, but I think we should also make it easier to pass the certs to the docker container as well, maybe as setting /etc/pure-fa-om-exporter as the default path in dockerfile like I did in #71

**Comment by chrroberts-pure** [comment]
I have to revert the TLS Support because it needs additional documentation. I will get to testing, and then @sdodsley we can merge this and #71. Please merge this one first after I confirm with testing.

**Comment by chrroberts-pure** [comment]
tested and ready to merge @sdodsley

**Review by chrroberts-pure — APPROVED** [review]
approved after backing out TLS support feature, that will need to be submitted as a new PR

**Pull request merged**
